recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeCreateView,
    RecipeDeleteView,
    RecipeUpdateView,
    create_shopping_item,
    delete_shopping_list,
    log_rating,
    RecipeDetailView,
    RecipeListView,
    ShoppingListView,
)

urlpatterns = [
    path("", RecipeListView.as_view(), name="recipes_list"),
    path("<int:pk>/", RecipeDetailView.as_view(), name="recipe_detail"),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe_delete"),
    path("new/", RecipeCreateView.as_view(), name="recipe_new"),
    path("<int:pk>/edit/", RecipeUpdateView.as_view(), name="recipe_edit"),
    path("<int:recipe_id>/ratings/", log_rating, name="recipe_rating"),
    path(
        "shopping_items/create",
        create_shopping_item,
        name="shopping_item_create",
    ),
    path(
        "shopping_items/delete/",
        delete_shopping_list,
        name="delete_all_shopping_items",
    ),
    path(
        "shopping_items", ShoppingListView.as_view(), name="shopping_item_list"
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("meal_plans/", include("meal_plans.urls")),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagCreateView,
    TagListView,
    TagDetailView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit", TagUpdateView.as_view(), name="tag_edit"),
    path("<int:pk>/delete", TagDeleteView.as_view(), name="tag_delete"),
]

recipes/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=125)
    author = models.ForeignKey(
        USER_MODEL, related_name="recipes", on_delete=models.CASCADE, null=True
    )
    description = models.TextField()
    image = models.URLField(null=True, blank=True, max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    servings = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(50)], null=True
    )

    """the __str__ method, is what gets called by Python when it wants to turn
    it into a string. You can use any of the properties
    that you defined in the __str__ method."""

    def __str__(self):
        return self.name


class Measure(models.Model):
    name = models.CharField(max_length=30, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.abbreviation


class FoodItem(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    amount = models.FloatField()
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ingredients",
        on_delete=models.CASCADE,
        null=True,
    )
    measure = models.ForeignKey(
        "Measure", related_name="ingredients", on_delete=models.PROTECT
    )
    food_item = models.ForeignKey(
        "FoodItem", related_name="ingredients", on_delete=models.PROTECT
    )

    def __str__(self):
        return f"{self.amount} + {self.measure} + {self.food_item}"


class Step(models.Model):
    recipe = models.ForeignKey(
        "Recipe", related_name="steps", on_delete=models.CASCADE, null=True
    )
    order = models.PositiveSmallIntegerField()
    directions = models.CharField(max_length=300)

    def __str__(self):
        return f"{self.order} + {self.directions}"


class Rating(models.Model):
    value = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    recipe = models.ForeignKey(
        "Recipe", related_name="ratings", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.value} {self.recipe}"


class ShoppingItem(models.Model):
    user = models.ForeignKey(
        USER_MODEL, related_name="shopping_item", on_delete=models.CASCADE
    )
    food_item = models.ForeignKey(
        FoodItem, related_name="shopping_item", on_delete=models.PROTECT
    )

    def __str__(self):
        return f"{self.user} {self.food_item}"

recipes/forms.py
from django import forms
from recipes.models import Rating

# try:
# from recipes.models import Recipe


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["value"]

recipes/views.py
from django.shortcuts import redirect
from recipes.forms import RatingForm
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy
from django.db import IntegrityError

from recipes.models import Recipe, ShoppingItem, Ingredient
from django.contrib.auth.mixins import LoginRequiredMixin


def log_rating(request, recipe_id):
    if request.method == "POST":
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            try:
                rating.recipe = Recipe.objects.get(pk=recipe_id)
                rating.save()
            except Recipe.DoesNotExist:
                return redirect("recipes_list")
    return redirect("recipe_detail", pk=recipe_id)


# UPDATE: SWITCH TO USING CLASSES BELOW:


class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/list.html"
    paginate_by = 2


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()

        # Create a new empty list and assign it to a variable
        foods = []

        # For each item in the user's shopping items, which we
        # can access through the code
        users_items = self.request.user.shopping_item.all()

        for item in users_items:
            # Add the shopping item's food to the list
            foods.append(item.food_item.name)

        # The self.request.GET property is a dictionary
        # Get the value out of there associated with the
        #   key "servings"
        # Store in the context dictionary with the key
        #   "servings"
        context["servings"] = self.request.GET.get("servings")

        # Put that list into the context
        context["food_in_shopping_list"] = foods
        return context


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipes/new.html"
    fields = [
        "name",
        "description",
        "image",
        "servings",
    ]
    success_url = reverse_lazy("recipes_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = "recipes/edit.html"
    fields = [
        "name",
        "description",
        "image",
        "servings",
    ]
    success_url = reverse_lazy("recipes_list")


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = "recipes/delete.html"
    success_url = reverse_lazy("recipes_list")


class ShoppingListView(LoginRequiredMixin, ListView):
    model = ShoppingItem
    template_name = "recipes/shoppinglist.html"
    context_object_name = "shopping_list"

    # Filter to only show shopping list to corresponding logged in user
    def get_queryset(self):
        return ShoppingItem.objects.filter(user=self.request.user)


def create_shopping_item(request):
    # Get the value for the "ingredient_id" from the
    # request.POST dictionary using the "get" method
    ingredient_id = request.POST.get("ingredient_id")

    # Get the specific ingredient from the Ingredient model
    # using the code
    # Ingredient.objects.get(id=the value from the dictionary)
    ingredient = Ingredient.objects.get(id=ingredient_id)

    # Get the current user which is stored in request.user
    user = request.user

    try:
        # Create the new shopping item in the database
        ShoppingItem.objects.create(food_item=ingredient.food_item, user=user)
    except IntegrityError:
        pass

    # Go back to the recipe page with a redirect
    # to the name of the registered recipe detail
    # path with code like this
    # return redirect(
    #     name of the registered recipe detail path,
    #     pk=id of the ingredient's recipe
    # )
    return redirect("recipe_detail", pk=ingredient.recipe.id)


def delete_shopping_list(request):
    # Delete all of the shopping items for the user
    # using code like
    ShoppingItem.objects.filter(user=request.user).delete()

    # Go back to the shopping item list with a redirect
    # to the name of the registered shopping item list
    # path with code like this
    return redirect("shopping_item_list")

recipes/templates/recipes/delete.html
{% extends 'base.html'%} {% block content%}
<main>
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ recipe.name }}"?</p>
    {{ form.as_p }}
    <div class="control">
      <button class="button">Delete</button>
    </div>
  </form>
</main>
{% endblock content %}

recipes/templates/recipes/detail.html
{% extends "base.html" %} {% load markdownify %} {% load custom_filters %}
{%block content %}
<main class="recipe-detail">
  <div>
    <a href="{% url 'recipes_list' %}">Back</a>
    {% if request.user == recipe.author %}
    <a href="{% url 'recipe_edit' recipe.id %}">Edit</a>
    <a href="{% url 'recipe_delete' recipe.id %}">Delete</a>
    {% endif %}
  </div>
  {% if recipe.image %}
  <img src="{{ recipe.image }}" class="pull-right" />
  {% endif %}
  <h1>{{ recipe.name }}</h1>
  <h4>by: {{ recipe.author | default_if_none:"Unknown" }}</h4>
  <p>Created on {{ recipe.created }} | Updated on {{ recipe.updated }}</p>
  {% if recipe.servings %}
  <p>Serves {{ recipe.servings }}</p>
  <form method="GET">
    <input type="number" name="servings" required />
    <button class="button">Resize</button>
    {% endif %} <form method="post" action="{% url "recipe_rating" recipe.id
    %}"> {% csrf_token %} {{ rating_form.as_p }}
    <button class="button">Rate</button>
  </form>
  <p>
    <a href={% url 'tags_list' %}>Tags:</a> {% for tag in recipe.tags.all %}
    <a href="{% url 'tag_detail' tag.pk %}">{{ tag.name }}</a>
    {% endfor %}
  </p>
  <a href="{% url 'tag_new' %}">Add New Tag</a>
  {{ recipe.description | markdownify }}
  <h2>Ingredients</h2>
  <table>
    <thead>
      <tr>
        <th colspan="2">Amount</th>
        <th>Food item</th>
      </tr>
    </thead>
    <tbody>
      {% for ingredient in recipe.ingredients.all %}
      <tr>
        <td>{{ ingredient|resize_to:servings }}</td>
        <td>{{ ingredient.measure.name }}</td>
        <td>{{ ingredient.food_item.name }}</td>
        <td>
          {% if ingredient.food_item.name not in food_in_shopping_list %}
          <!-- only show this if the ingredient food is not in the shopping list -->
          <form method="POST" action="{% url 'shopping_item_create' %}">
            {% csrf_token %}
            <input
              type="hidden"
              name="ingredient_id"
              value="{{ ingredient.id }}"
            />
            <button>+ shopping list</button>
          </form>
          <!-- otherwise, show the message "in your list" -->
          {% else %} in your list {% endif%}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <h2>Steps</h2>
  <ol>
    {% for step in recipe.steps.all %}
    <li>{{ step.directions }}</li>
    {% endfor %}
  </ol>
</main>
{% endblock content %}

recipes/templates/recipes/edit.html
<!DOCTYPE html>
{% extends 'base.html' %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>
{% endblock content %}

recipes/templates/recipes/list.html
{% extends "paginate.html" %} {% block content %}
<main class="recipe-grid">
  {% for recipe in recipe_list %}
  <div class="recipe-card">
    <h2 class="recipe-card-title">
      <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
    </h2>
    <p class="recipe-card-date">{{ recipe.updated }}</p>
  </div>
  {% endfor %}
</main>
{% endblock content%}

recipes/templates/recipes/new.html
{% extends "base.html" %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}

recipes/templates/recipes/shoppinglist.html
{% extends 'base.html' %} {% block content %}
<main class="recipe-detail">
  <a href="{% url 'recipes_list' %}">Back</a>
  <br />
  <h1>Your Shopping List</h1>
  <ul>
    {% for item in shopping_list %}
    <li>{{ item.food_item }}</li>
    {% empty %}
    <p>No items in your shopping list</p>
    {% endfor %}
  </ul>
  <br />
  <div>
    <form method="post" action="{% url 'delete_all_shopping_items' %}">
      {% csrf_token %}
      <button class="button">Delete All</button>
    </form>
  </div>
</main>

{% endblock content%}